config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'

  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  get 'users/:id', to: 'users#show', as: 'user'
  get 'users', to: 'users#index'
  get 'users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch 'users/:id', to: 'users#update'
  delete 'users/:id', to: 'users#destroy'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :postlinks, only: [:create, :destroy]

end

app/models/postlink.rb
class Postlink < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :postlinks, dependent: :destroy
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true

  def feed
    Postlink.where("user_id = ?", id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in"
      redirect_to login_url
    end    
  end
end

app/controllers/postlinks_controller.rb
class PostlinksController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def create
    @postlink = current_user.postlinks.build(postlink_params)
    if @postlink.save?
      flash[:success] = "Postlink created"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    
  end

  private

  def postlink_params
    params.require(:postlink).permit(:title, :link, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged Out Successfully'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @postlink = current_user.postlinks.build if logged_in?
    if logged_in?
      @postlink = Postlink.new
      @feed_items = current_user.feed.paginate(page: params[:page], per_page: 7)
    end
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page], per_page: 10) 
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @postlinks = @user.postlinks.paginate(page: params[:page], per_page: 10)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
      if @user.save
        log_in @user
        flash[:succes] = "Welcome to Savefood !"
        redirect_to @user
      else
        render 'new'
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:succes] = "Profile updated"
      redirect_to user
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :comfirmation_password)
    end
    
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/postlinks_helper.rb
module PostlinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
   def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",  about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://github.com/nickiesiva">Github</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Wretlinks", '/', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   '/' %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "About",   about_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= yield(:title) %> | Write Your Links</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>

</body>
</html>

app/views/postlinks/_postlink.html.erb
<li id="postlink-<%= postlink.id %>">
  <%= link_to gravatar_for(postlink.user, size: 50), postlink.user %>
  <span class="content">
    <span class="user"><%= link_to postlink.user.name, postlink.user %></span><br>
    <strong><em><a href="<%= postlink.link %>"><%= postlink.title %></a></em></strong><br>                                                 
    <%= postlink.description %>                                                                                                            
  </span><br>
  <span class="timestamp">
    Posted <%= time_ago_in_words(postlink.created_at) %> ago.
  </span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="postlinks">
    <%= render @feed_items %>
  </ol>

  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_postlink_form.html.erb
<%= form_for(@postlink) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :title, placeholder: "Title" %>
    <%= f.text_field :link, placeholder: "Link" %>
    <%= f.text_area :description, placeholder: "Description about your link..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.postlinks.count, "postlink") %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>Wretlinks Apps</h1>
<p>Write and Save your links here !</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Wretlinks</h1>
<p>If you need some help, please contact me.</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/postlink_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Postlinks Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Wretlinks Apps !</h1>

    <h2>This is the home page for the<a href="users#home"> Wretlinks </a>application.</h2>
    <h2>Write and Save your links here !</h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target=_blank>change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<h1>All Users</h1>

<%= will_paginate %>

<table class="table">
  <% @users.each do |user| %>
  <tr>
    <td>
      <%= gravatar_for user, size: 50 %>
    </td>
    <td>
      <%= link_to user.name, user %>
    </td>
    <td>
      <%= user.email %>
    </td>
    <% if current_user.admin? %>
      <td>
        <%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    <% end %>
  </tr>
  <% end %>
</table>

<%= will_paginate %>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>

<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create My Account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <%= link_to 'Edit', edit_user_path(@user) %> |
      <%= link_to 'Back', users_path %>
    </section>
  </aside>


  <div class="col-md-8">
    <h3>Postlinks (<%= @user.postlinks.count %>)</h3> 
    <ul class="postlinks">
      <% @postlinks.each do |postlink| %>
        <li>
          <%= link_to gravatar_for(postlink.user, size: 50), postlink.user %>
          <span class="user"><%= link_to postlink.user.name, postlink.user %></span><br>
          <span class="content">
            <strong><em><a href="<%= postlink.link %>"><%= postlink.title %></a></em></strong><br>
            <%= postlink.description %>
          </span>
          <span class="timestamp">
            Posted <%= time_ago_in_words(postlink.created_at) %> ago.
          </span>
        </li>
      <% end %>
    </ul>
    <%= will_paginate @postlinks %>
  </div>
</div>